Follower list
wwi21seb-projekt/Schnatter pull request #68
Opened 2024-01-24 17:25 UTC by mabu2807

2024-01-24 19:43 UTC, Nora01K commented on src/components/layout/navbar.svelte
>  			{/if}
das ende vom if muss hinter den teil von dem profil-button

2024-01-24 19:54 UTC, Nora01K commented on src/lib/types/Subscriptions.ts
> +		| [
oder weg machen

2024-01-24 20:15 UTC, Nora01K commented on src/components/userLists/SubscriptionList.svelte
> +	<!-- (optionally you can provide a label here) -->
weg

2024-01-24 20:17 UTC, Nora01K commented on src/components/userLists/SubscriptionList.svelte
> +		<!-- ... -->
wofür das ?

2024-01-24 20:22 UTC, Nora01K requested changes
#Checkliste Code

- [x] Gibt es keine offensichtliche Logikfehler im Code 
- [x] Sind alle Variablen/Methoden etc. richtig und sprechend benannt (siehe Coding Guidelines -> Benennung)
- [werden von dennis im noch angepasst] Sind alle relevant Tests geschrieben ("relevant" siehe Code-Guidelines -> Tests)
- [ siehe Kommentare] Sind alle zuvor besprochenen Fehlerfälle abgedeckt? (StatusCodes)
- [x] Gibt es keine Code-Duplikationen (bsp schon implementierte Teile in Komponenten)
- [x] UI ist einheitlich (siehe Mockups) und Farben sind verwendet wie in Theme beschrieben 
- [x] Ist die Codelänge in Ordnung? Wenn nein, wo gibt es Verbesserungspotenzial:

- [x] Ist der Code verständlich geschrieben, wenn Nein an welchen Stellen ist er zu kompliziert:


- Allgemeine Kommentare:
- den load-more button auf dem profil bitte mittig

2024-01-25 09:31 UTC, lisaress approved these changes

2024-01-25 16:19 UTC, Nora01K approved these changes

2024-01-25 16:19 UTC, merged